project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: rego.qmd
        text: Registration
      - href: schedule.qmd
        text: Schedule
  page-navigation: true

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

