---
title: "Adelaide Data Privacy Workshop"
---

**November 26--27th, 2025** at the **University of Adelaide**

Organised by [Dr Joshua Bon](https://bonstats.github.io) 

------------------------------------------------------------------------

The [School of Computer and Mathematical Sciences](https://set.adelaide.edu.au/computer-and-mathematical-sciences/) and [Adelaide Data Science Centre](https://set.adelaide.edu.au/adelaide-data-science-centre/) invite you to join the Adelaide Data Privacy Workshop held **26--27th November 2025** at the University of Adelaide.

### Join us!

::: {.callout-important}
## Registration

Registration for the workshop will close on Monday 17th of November.
:::

This two-day event explores the foundations of data privacy across mathematics, statistics, and computer science. Researchers, students, and practitioners who work in --- or wish to learn more about --- data privacy are warmly invited to participate.

```{r, echo = FALSE, warning = FALSE, message=FALSE}
library(wordcloud)
library(RColorBrewer)

words <- c("data privacy", "differential privacy", "federated learning", "homomorphic encryption", "secure multi-party computation","Bayesian statistics", "game theory", "statistical computation", "machine learning", "artificial intelligence", "Rényi DP", "zero-concentrated DP", "f-DP", "synthetic data", "randomized response", "distributed data")

freq = c(100, 30, 30, 30, 15, 15, 15, 15, 15, 15, 10, 10, 10, 30, 15,15)


wordcloud(words = words, freq = freq, scale=c(5,0.5), random.order = FALSE, random.color = TRUE,  colors=brewer.pal(8, "Dark2"), rot.per = 0)

```


### Program

We are delighted to host [Prof. Murray Pollock](https://www.ncl.ac.uk/maths-physics/people/profile/murraypollock.html) (Newcastle University, UK) and [Dr. James Bailie](https://jameshbailie.github.io) (Chalmers University of Technology, Sweden), who will share their expertise on Bayesian data fusion, federated learning, and the mathematics of data privacy. 

In addition to these keynotes, the program will include contributed talks at the frontier of data privacy theory and exploring fundamental methods that ensure data privacy.

The [full program](schedule.qmd) will also enjoy opportunities for discussions and networking.



### Registration and abstract submission

Registration[^1] and abstract submission can be found [here](rego.qmd).


[^1]: Registration is free but mandatory!
